### ISSUE TITLE
Add trademark notice

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/heteronculous-horklump#10]
Since Namecoin does not possess a trademark license from Tor, we should probably put a trademark notice at the bottom of the README.  It can be adapted from the one on the footer of Namecoin.org's website.  Below the copyright notice ( https://github.com/namecoin/heteronculous-horklump/issues/3 ) seems a reasonable place to put it.  It doesn't need to be in the source code, just the README is fine.

**Comment by JeremyRand** [comment]
For consistency, maybe substitute `heteronculous-horklump` for `Namecoin` like you did for the copyright notice?

**Comment by robertmin1** [comment]
@JeremyRand Where specifically? The footer doesn't contain  heteronculous-horklump
