### ISSUE TITLE
Hardcoded Unix socket path?

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/heteronculous-horklump#13]
It looks like there's a hardcoded Unix socket path that's whitelisted: https://github.com/namecoin/heteronculous-horklump/blob/37ac0e6e05c05f6afcfa5ea9f09cc49ee666f1ad/main.go#L62

If there's a reason this particular path is whitelisted, that should probably be documented.  Otherwise, we should probably ponder whether we have any reason to intercept Unix sockets.  They shouldn't cause a direct proxy leak.  They *could* cause a stream isolation leak, but the relevant code paths in the tracer for that case would be the same as for a TCP socket that's talking to the whitelisted SOCKS port.  So I think we can whitelist all Unix sockets on the above referenced line rather than checking for specific paths.

Let me know if you think I've missed something.

**Comment by robertmin1** [comment]
The default will be set to block the syscall, other alternatives will be added through easyconfig.
