### ISSUE TITLE
Factor out each syscall handler into a separate function

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/heteronculous-horklump#15]
It seems like the code would be cleaner if the handler for each syscall were a separate function.  E.g. a `HandleConnect` function could contain this portion of the code: https://github.com/namecoin/heteronculous-horklump/blob/37ac0e6e05c05f6afcfa5ea9f09cc49ee666f1ad/main.go#L58-L99

This would keep each function smaller (and with less indentation) and make it easier to follow the code.

**Comment by robertmin1** [comment]
@JeremyRand Okay! That will also fix some of the Go Lint Issues
