### ISSUE TITLE
Move more logic into SetEnv

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/heteronculous-horklump#25]
In https://github.com/namecoin/heteronculous-horklump/blob/c934609549201d12c84a0a0aed87ff92783a8fd2/main.go#L64-L66 , we currently have a lot of logic that gets processed before passing data to `SetEnv`.  For example, the choice of which config options are affected, and which environment variables are read.  In the future, we will support more Tor environment variables (e.g. for Unix sockets and incoming connections), which will make the current code become unwieldy.

I suggest making `SetEnv` accept a single argument of type `Config`, and handle the logic of reading environment variables inside `SetEnv`.

**Comment by robertmin1** [comment]
The issue will be closed after issue #29
