### ISSUE TITLE
BlockSyscall needs more comments

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/heteronculous-horklump#27]
In https://github.com/namecoin/heteronculous-horklump/blob/c934609549201d12c84a0a0aed87ff92783a8fd2/main.go#L219-L252 , it is not clear to a casual reader what this code is doing.  I think what it's trying to do is use ptrace commands to change the state of the tracee, and then use wait commands to let the tracee do stuff, but in both of those cases, each command should have a comment explaining what state change is happening.  (I suspect I see a race condition in this function too, but I can't really be certain without understanding what precisely the code is intending to do -- a good example of documentation making audits easier.)

Also (unless I'm misreading) the `wait4` manpage says that it's deprecated and shouldn't be used, maybe replace that usage?

**Comment by robertmin1** [comment]
@JeremyRand  adviced using  waitid(2) instead of wait4
