### ISSUE TITLE
Add copyright notice

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/heteronculous-horklump#3]
FSF recommends a copyright notice, both at the bottom of the README and at the top of each source code file.  The README notice can be adapted from https://github.com/namecoin/certinject/blob/0f148ec7379980464370817c9d418fe0c342d572/README.md?plain=1#L61-L76 ;  the source code notice can be adapted from https://github.com/namecoin/safetlsa/blob/90fef85b9522406073646dc8385cbda521f033a3/config.go#L1-L17 .

**Comment by JeremyRand** [comment]
Notice at the top of https://github.com/namecoin/heteronculous-horklump/blob/e72d0eda803dbc0da50a4a039ce1decde3294d5b/main.go looks good to me, still need to add it to the bottom of the README.

**Comment by robertmin1** [comment]
@JeremyRand  I did add the Notice in the README (Under the Licence, similar to pkcs11mod)

**Comment by JeremyRand** [comment]
Ah, indeed, not sure how I missed it.  Maybe I was looking at the wrong branch.  v0v
