### ISSUE TITLE
SOCKS authentication for SOCKSification

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/heteronculous-horklump#40]
When the tracer is performing a SOCKS5 handshake, it should include a SOCKS5 username+password. A reasonable approach to picking one would be:

1. When the tracer first launches (before starting the tracee), the tracer generates 384 bits of cryptographic-grade random data.
2. The random data is encoded as hex.
3. The hex-encoded random data (96 hex digits) is used as a SOCKS5 username for all SOCKS5 operations issued by the tracer.
4. A similar approach is used to generate a SOCKS5 password.

This has the following benefits:

* Every application is isolated from every other application. (Better than a Trans proxy.)
* Restarting an application will result in a new Tor circuit. (Better than using the application name as the username.)
* The username is high-entropy and therefore will not accidentally be reused. 384 bits is secure against Grover collision attacks. (Better than using the PID as the username, as torsocks does.)
* The username does not reveal anything about the application to the Tor daemon, which is useful for Whonix-style threat models. (Better than using the first-party hostname as the username, as Tor Browser does.)

**Comment by robertmin1** [comment]
Implemented using crypto/rand
