### ISSUE TITLE
Usage of math/rand may be problematic

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/heteronculous-horklump#43]
This usage of `math/rand` may be a security risk:

https://github.com/robertmin1/heteronculous-horklump/blob/fe0fa005b074e0464c856940333eee02e874ae57/main.go#L37

While I can't immediately see any attack that predictable SOCKS authentication slot assignment enables, I also can't immediately convince myself that there's no possible attack. There's a long history of usage of insecure primitives (that were believed to be OK in the given context) causing security vulns later (see MD5 in TLS certificates), so I think I'd prefer that this usage be replaced with `crypto/rand`.

If there's some specific reason that `crypto/rand` is unsuitable, then that reason should at least be documented.

**Comment by robertmin1** [comment]
math/rand seemed to be cleaner, I'll do a crypto/rand implementation.
