### ISSUE TITLE
Make "Redirect" config a string

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/heteronculous-horklump#45]
Currently, `Config.Redirect` is a `bool`, and controls both the redirect behavior and the SOCKS handshake: https://github.com/robertmin1/heteronculous-horklump/blob/fe0fa005b074e0464c856940333eee02e874ae57/main.go#L79

It would be useful to change it to a string. The possible values would be:

* `socks5`: Same as current behavior.
* `http`: Performs an HTTP CONNECT handshake instead of a SOCKS5 handshake. This would allow usage with HTTP-based proxies.
* `trans`: Redirects the socket without prepending any handshake. This would allow usage with proxies that auto-detect the destination from the SNI Host header. (While this use case is certainly becoming less relevant now that ECH is becoming a thing, it's still reasonable to support since it doesn't take much extra code.)

**Comment by robertmin1** [comment]
Implemented.
Trans proxy:TODO
