### ISSUE TITLE
Proxyusr+Proxypas abbreviations are less readable

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/heteronculous-horklump#46]
The `Proxyusr` and `Proxypas` abbreviations ( https://github.com/robertmin1/heteronculous-horklump/blob/fe0fa005b074e0464c856940333eee02e874ae57/main.go#L80-L81 ) are somewhat nonstandard and difficult to read. I think expanding to `Proxyuser` and `Proxypass` would be more readable and more in line with standard convention.

**Comment by robertmin1** [comment]
Using Proxyuser and Proxypass instead
