### ISSUE TITLE
GenerateRandomCredentials errors not being checked

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/heteronculous-horklump#47]
In a couple places, the error returned by `GenerateRandomCredentials` is discarded:

* https://github.com/robertmin1/heteronculous-horklump/blob/fe0fa005b074e0464c856940333eee02e874ae57/main.go#L113-L116
* https://github.com/robertmin1/heteronculous-horklump/blob/fe0fa005b074e0464c856940333eee02e874ae57/main.go#L486-L487

This seems dangerous, as it will cause stream isolation to be silently disabled if the PRNG fails for some reason.

**Comment by robertmin1** [comment]
Implemented, but the error will be handled through panic, since it's not in the strace.Trace funciton.
A warning can also be used, but panic might be better

**Comment by robertmin1** [comment]
Checking the errors
