### ISSUE TITLE
Enable `nlreturn` linter

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/heteronculous-horklump#52]
Can we re-enable the `nlreturn` linter as mandatory? https://github.com/namecoin/heteronculous-horklump/blob/bffb3c9a02464e3d716a2e9f90ecbb95407074bf/.cirrus.yml#L19

This should be pretty easy to pass (though we don't pass right now), and it'll make the code a bit more readable.

**Comment by robertmin1** [comment]
Implemented [here](https://github.com/namecoin/heteronculous-horklump/commit/f0ca4a57c01f4bf148acf0ba5854f8fd4c670db2)
