### ISSUE TITLE
Log PID and process name when leak detected

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/heteronculous-horklump#64]
Currently, the log output doesn't show which process triggered a leak. This makes it difficult to debug things. Logging the PID and process name (e.g. `/usr/bin/tor`) would be nice.

**Comment by robertmin1** [comment]
```
func logLeak(programName string, pid int) {
// Logging the leak information with PID and process name to a file
logfile, err := os.OpenFile("/usr/bin/hork", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
if err != nil {
      log.Fatal(err)
}
defer logfile.Close()

logger := log.New(logfile, "", log.LstdFlags)
logger.Printf("Leaked pointer detected by process %v (%v), PID %v\n", programName, pid, leakedPtr)
}
```

**Comment by robertmin1** [comment]
This is what I've been considering, however, it needs su permissions. 
I must modify the name of the 'log' package since I am using it here and it will interfere with xlog.
The `xlog package` would be simpler for me to utilize, I am not yet sure how to log one line to a file.

**Comment by robertmin1** [comment]
@JeremyRand Suggested to use `cmdline` since it provides additional information

**Comment by robertmin1** [comment]
During testing it produced `Trace/breakpoint` errors.

**Comment by robertmin1** [comment]
Change to the file storage location can be considered
