### ISSUE TITLE
Consider avoiding goxsys/unix for killing process

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/heteronculous-horklump#7]
Is there a reason you're using `goxsys/unix` here?  https://github.com/namecoin/heteronculous-horklump/blob/e72d0eda803dbc0da50a4a039ce1decde3294d5b/main.go#L61

Seems like the `os.Process.Kill` function would be preferable, since it's in the Go standard library and is likely to have a stabler API and better QA testing than `goxsys`.  (Also I think `SIGKILL` is the right signal to use, not `SIGSTOP,` since `SIGKILL` guarantees that the program won't be able to ignore the signal.   But let me know if you think I've overlooked a good reason to use `SIGSTOP`.)

**Comment by robertmin1** [comment]
@JeremyRand It was changed to utilize Go standard libraries as well as the SIGKILL command. The option of killing an application in case of a proxy leak has also been implemented.
